# Generated by Django 6.0.3 on 2026-03-28 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('canal', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('transcripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id_resumen', models.AutoField(primary_key=True, serialize=False)),
                ('resumen_texto', models.TextField(blank=True, null=True)),
                ('video', models.ForeignKey(blank=True, db_column='video_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='noticias.video')),
            ],
            options={
                'db_table': 'resumen',
            },
        ),
    ]
